{{- if and .Values.admin.enabled (not .Values.postgres.existingSecret) }}
{{- $dsn := .Values.postgres.dsn -}}
{{- if not $dsn -}}
{{- $dsn = printf "postgres://%s:%s@%s:%v/%s?sslmode=%s" .Values.postgres.user .Values.postgres.password .Values.postgres.host (.Values.postgres.port | int) .Values.postgres.database .Values.postgres.sslmode -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-db" (include "pulsys.fullname" .) }}
  labels:
    {{- include "pulsys.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ $dsn | quote }}
{{- end }}
