{{- if and .Values.admin.enabled .Values.oidc.enabled (not .Values.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-oidc" (include "pulsys.fullname" .) }}
  labels:
    {{- include "pulsys.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.oidc.clientSecret | quote }}
{{- end }}
