#!/usr/bin/env bash
# bench_saturate.sh -- demonstrate full utilization of the bench host.
#
# Primary deliverable for the full-machine saturation goal: prove pulsys can
# drive every vCPU on the instance it runs on (c7i.12xlarge by default, or any
# larger virt/metal SKU) while publishing throughput + CPU utilization
# evidence.  Instance type and vCPU count are read at run time and recorded in
# the report + headline.json, so the numbers always describe the box they were
# measured on.
#
# What this runs:
#
#   * pulsys with PULSYS_VARIANT=saturate
#       (NUMA shards + SO_REUSEPORT listeners on all cores per shard)
#   * wrk with BENCH_WRK_THREADS=max (one wrk thread per vCPU)
#   * conns = 4 * vCPU by default (enough in-flight work to keep cores busy)
#   * payloads 4k 256k 4m 16m (HF-realistic; no 64m on the chart path)
#   * mpstat captured every cell -> aggregate %CPU busy in saturate-report.md
#
# Skips DingoSpeed (this is a utilization demo, not a head-to-head matrix).
#
# Usage:
#   scripts/bench_saturate.sh                    # default 30s per cell
#   scripts/bench_saturate.sh 60s                # longer per cell
#   CONNS=512 scripts/bench_saturate.sh          # override connection count
#
# On the AMI / via SSM (io_uring variant):
#   scripts/ssm-bench.sh variant=saturate-iouring duration=30s
#
# Outputs:
#   tmp/bench/matrix.csv              (tagged pulsys-saturate)
#   tmp/bench/saturate-report.md      (human-readable utilization summary)
#   tmp/bench/logs/mpstat_*.txt       (raw per-cell mpstat)
#
# Prints SATURATE_ARTIFACT=<path> for SSM upload (tarball of report + logs).
set -euo pipefail
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BENCH="$ROOT/tmp/bench"
LOGS="$BENCH/logs"
REPORT="$BENCH/saturate-report.md"
DURATION="${1:-30s}"

NCpu="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"
# Enough keep-alive connections that every core has work; override with CONNS=.
CONNS="${CONNS:-$(( NCpu * 4 ))}"
PAYLOADS="${PAYLOADS:-4k 256k 4m 16m}"
ROUNDS="${ROUNDS:-3}"

# Provenance for a self-certifying report: kernel (io_uring requires >= 6.1)
# and EC2 instance type (best-effort IMDSv2; empty off-EC2). Never fail the run.
KERNEL="$(uname -r 2>/dev/null || echo unknown)"
INSTANCE_TYPE="$(
	( tok="$(curl -fsS -m 1 -X PUT 'http://169.254.169.254/latest/api/token' \
		-H 'X-aws-ec2-metadata-token-ttl-seconds: 60' 2>/dev/null)" \
		&& curl -fsS -m 1 -H "X-aws-ec2-metadata-token: $tok" \
			'http://169.254.169.254/latest/meta-data/instance-type' 2>/dev/null ) || true
)"
[ -n "$INSTANCE_TYPE" ] || INSTANCE_TYPE="unknown (not on EC2 / IMDS unavailable)"

# Server-shape variant. Default = saturate-no-cork (loopback: TCP_CORK buys
# nothing and costs 2 setsockopt/response).  Use SATURATE_VARIANT=saturate for
# cork-on A/B; rows are tagged pulsys-<variant> in matrix.csv.
export PULSYS_VARIANT="${SATURATE_VARIANT:-saturate-no-cork}"
case "$PULSYS_VARIANT" in
	saturate|saturate-no-cork|saturate-iouring) ;;
	*)
		echo "FATAL: SATURATE_VARIANT must be saturate|saturate-no-cork|saturate-iouring (got $PULSYS_VARIANT)" >&2
		exit 2
		;;
esac
export BENCH_WRK_THREADS=max
export BENCH_CAPTURE_MPSTAT=1
export BENCH_SKIP_DINGOSPEED=1

# io_uring is only requested by the *-iouring variant; on other variants the
# warm path uses cork/sendfile. Engagement is confirmed post-run via the
# pulsys_io_uring_fused_calls counter (see "Reproducing benchmarks" doc).
case "$PULSYS_VARIANT" in
	*iouring) IOU_STATUS="requested (\`-iouring=true\`); verify \`pulsys_io_uring_fused_calls\` > 0 on the admin listener" ;;
	*)        IOU_STATUS="off (cork/sendfile warm path)" ;;
esac

mkdir -p "$LOGS"

echo "==> bench_saturate: ${NCpu} vCPU, conns=${CONNS}, duration=${DURATION}" >&2
echo "    payloads=${PAYLOADS}  rounds=${ROUNDS}" >&2

bash "$ROOT/scripts/bench_matrix.sh" \
	"$PAYLOADS" \
	"$CONNS" \
	warm \
	"$ROUNDS" \
	"$DURATION"

# ----- parse mpstat -> utilization summary --------------------------------
avg_mpstat_busy() {
	# Average (100 - %idle) across per-CPU lines, excluding the "all" row.
	awk '
		/^[0-9][0-9]:/ && $2 ~ /^[0-9]+$/ {
			idle = $(NF)
			busy += (100 - idle)
			n++
		}
		END {
			if (n > 0) printf "%.1f", busy / n
			else print "0"
		}
	' "$1"
}

peak_mpstat_busy() {
	awk '
		/^[0-9][0-9]:/ && $2 ~ /^[0-9]+$/ {
			idle = $(NF)
			b = 100 - idle
			if (b > max) max = b
		}
		END { printf "%.1f", max + 0 }
	' "$1"
}

cores_over_threshold() {
	# Count CPU samples where busy >= threshold (default 50%).
	local thresh="${2:-50}"
	awk -v t="$thresh" '
		/^[0-9][0-9]:/ && $2 ~ /^[0-9]+$/ {
			idle = $(NF)
			if ((100 - idle) >= t) hot++
			total++
		}
		END {
			if (total > 0) printf "%.0f", 100 * hot / total
			else print "0"
		}
	' "$1"
}

{
	echo "# Saturation report"
	echo
	echo "_Generated by \`scripts/bench_saturate.sh\` at $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
	echo
	echo "| Field | Value |"
	echo "|---|---|"
	echo "| instance type | ${INSTANCE_TYPE} |"
	echo "| kernel | ${KERNEL} |"
	echo "| vCPU | ${NCpu} |"
	echo "| wrk connections | ${CONNS} |"
	echo "| wrk threads | ${NCpu} (max) |"
	echo "| pulsys variant | ${PULSYS_VARIANT} (reuseport listeners, loopback) |"
	echo "| io_uring | ${IOU_STATUS} |"
	echo "| duration / cell | ${DURATION} |"
	echo "| payloads | ${PAYLOADS} |"
	echo
	echo "## Utilization (mpstat, per benchmark cell)"
	echo
	echo "Columns: **avg %busy** across all CPUs, **peak %busy** on any single CPU sample, **% samples ≥50% busy**."
	echo
	echo "| Payload | Round | Avg %CPU busy | Peak %CPU | Samples ≥50% busy |"
	echo "|---|---:|---:|---:|---:|"
} >"$REPORT"

for f in "$LOGS"/mpstat_pulsys_*_warm_c*.txt; do
	[ -f "$f" ] || continue
	# filename: mpstat_pulsys_4k_warm_c384_r1.txt
	base="$(basename "$f" .txt)"
	payload="$(echo "$base" | sed -n 's/mpstat_pulsys_\([^_]*\)_.*/\1/p')"
	round="$(echo "$base" | sed -n 's/.*_r\([0-9]*\)$/\1/p')"
	avg="$(avg_mpstat_busy "$f")"
	peak="$(peak_mpstat_busy "$f")"
	hot="$(cores_over_threshold "$f" 50)"
	echo "| ${payload} | ${round} | ${avg}% | ${peak}% | ${hot}% |" >>"$REPORT"
done

# Best row for headline numbers (median avg busy across rounds per payload).
echo >>"$REPORT"
echo "## Utilization summary (highest measured avg %CPU busy per payload)" >>"$REPORT"
echo >>"$REPORT"
for p in $PAYLOADS; do
	best=0
	for f in "$LOGS"/mpstat_pulsys_"${p}"_warm_c*.txt; do
		[ -f "$f" ] || continue
		avg="$(avg_mpstat_busy "$f")"
		# shellcheck disable=SC2072
		if awk -v a="$avg" -v b="$best" 'BEGIN{exit !(a>b)}'; then
			best="$avg"
		fi
	done
	echo "- **${p}**: ${best}% avg CPU busy (target: ≥80% on small payloads for a full-machine demo)" >>"$REPORT"
done

# ----- peak Gbps from matrix.csv (HN headline) ------------------------------
# bytes_per_s column is human-readable (MB/GB); parse to bits/s for Gbps.
peak_gbps="$(grep "${PULSYS_VARIANT}" "$BENCH/matrix.csv" 2>/dev/null \
	| awk -F, '
function xfer_bps(s,   n) {
	if (match(s, /([0-9.]+)/)) n = substr(s, RSTART, RLENGTH) + 0
	else return 0
	if (s ~ /[Gg][Bb]/) return n * 1e9 * 8
	if (s ~ /[Mm][Bb]/) return n * 1e6 * 8
	if (s ~ /[Kk][Bb]/) return n * 1e3 * 8
	return n * 8
}
{
	bps = xfer_bps($7)
	if (bps > max) { max = bps; pay = $2; conc = $4 }
}
END {
	if (max > 0) printf "%.2f %.3f %s %s", max/1e9, max/1e9/8, pay, conc
}' || true)"

# ----- peak req/s from matrix.csv (the "1M+ req/s" headline) -----------------
# Column 6 is requests/sec.  Smallest payloads (4k) hit the request-rate
# ceiling; largest payloads hit the byte-rate ceiling reported above.
peak_rps="$(grep "${PULSYS_VARIANT}" "$BENCH/matrix.csv" 2>/dev/null \
	| awk -F, '{ r=$6+0; if (r>m) { m=r; pay=$2; conc=$4 } } END { if (m>0) printf "%.0f %s %s", m, pay, conc }' || true)"

{
	echo "## Headline throughput (loopback, warm)"
	echo
	if [ -n "$peak_rps" ]; then
		rps_n="$(echo "$peak_rps" | awk '{print $1}')"
		rps_pay="$(echo "$peak_rps" | awk '{print $2}')"
		rps_conc="$(echo "$peak_rps" | awk '{print $3}')"
		rps_m="$(awk -v n="$rps_n" 'BEGIN{printf "%.2f", n/1e6}')"
		echo "- **Peak: ${rps_m}M req/s (${rps_n} req/s)** on payload \`${rps_pay}\`, concurrency ${rps_conc}"
	fi
	if [ -n "$peak_gbps" ]; then
		peak_bits="$(echo "$peak_gbps" | awk '{print $1}')"
		peak_gbs="$(echo "$peak_gbps" | awk '{print $2}')"
		peak_pay="$(echo "$peak_gbps" | awk '{print $3}')"
		peak_conc="$(echo "$peak_gbps" | awk '{print $4}')"
		echo "- **Peak: ${peak_bits} Gbps (${peak_gbs} GB/s)** — payload \`${peak_pay}\`, concurrency ${peak_conc}"
		echo "- Instance: ${INSTANCE_TYPE} · ${NCpu} vCPU · kernel ${KERNEL} · variant \`${PULSYS_VARIANT}\`"
		echo
	else
		echo "(no pulsys-saturate rows in matrix.csv)"
		echo
	fi
} >>"$REPORT"

echo >>"$REPORT"
echo "## Throughput (from matrix.csv)" >>"$REPORT"
echo >>"$REPORT"
echo '```' >>"$REPORT"
grep "${PULSYS_VARIANT}" "$BENCH/matrix.csv" 2>/dev/null \
	| awk -F, '{printf "%s c=%s r=%s  %s req/s  %s\n",$2,$4,$5,$6,$7}' \
	>>"$REPORT" || echo "(no matrix rows yet)" >>"$REPORT"
echo '```' >>"$REPORT"

echo >>"$REPORT"
echo "## How to read this" >>"$REPORT"
echo >>"$REPORT"
echo "- **Small payloads (4k, 256k)** are useful for checking request-rate scaling and CPU saturation." >>"$REPORT"
echo "- **Large payloads (4m, 16m)** are useful for checking page-cache to socket throughput." >>"$REPORT"
echo "- Loopback numbers can exceed ENA line rate; do not treat them as VPC or Internet throughput." >>"$REPORT"

echo "wrote $REPORT"

# ----- machine-readable headline (single source of truth for doc headlines) ---
# scripts/update_claims.sh injects these values into README/docs between
# markers, so re-running on a different instance size refreshes the prose
# automatically instead of needing a hand-edit.
HEADLINE_JSON="$BENCH/headline.json"
rps_n="$(printf '%s' "$peak_rps" | awk '{print $1+0}')"
rps_pay="$(printf '%s' "$peak_rps" | awk '{print $2}')"
gbps_bits="$(printf '%s' "$peak_gbps" | awk '{print $1+0}')"
gbps_gbs="$(printf '%s' "$peak_gbps" | awk '{print $2+0}')"
gbps_pay="$(printf '%s' "$peak_gbps" | awk '{print $3}')"
rps_m="$(awk -v n="${rps_n:-0}" 'BEGIN{printf "%.2f", n/1e6}')"
HEADLINE_COMMIT="$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
cat >"$HEADLINE_JSON" <<EOF
{
  "instance_type": "${INSTANCE_TYPE}",
  "vcpu": ${NCpu:-0},
  "kernel": "${KERNEL}",
  "variant": "${PULSYS_VARIANT}",
  "peak_rps": ${rps_n:-0},
  "peak_rps_millions": ${rps_m:-0},
  "peak_rps_payload": "${rps_pay:-}",
  "peak_gbps": ${gbps_bits:-0},
  "peak_gb_per_s": ${gbps_gbs:-0},
  "peak_gbps_payload": "${gbps_pay:-}",
  "duration_per_cell": "${DURATION}",
  "git_commit": "${HEADLINE_COMMIT}",
  "generated_utc": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF
echo "wrote $HEADLINE_JSON"

# Preserve saturate rows before a later bench_matrix overwrites matrix.csv.
# Append (not overwrite) so back-to-back saturate runs of different sub-variants
# (saturate, saturate-no-cork, saturate-iouring) accumulate into one chart.
if grep -q 'pulsys-saturate' "$BENCH/matrix.csv" 2>/dev/null; then
	if [ -f "$BENCH/matrix-saturate.csv" ]; then
		# Keep header from the existing snapshot, append only the new
		# rows for this variant.
		grep "${PULSYS_VARIANT}" "$BENCH/matrix.csv" >>"$BENCH/matrix-saturate.csv" || true
		echo "append: $BENCH/matrix-saturate.csv (+${PULSYS_VARIANT})"
	else
		cp "$BENCH/matrix.csv" "$BENCH/matrix-saturate.csv"
		echo "snapshot: $BENCH/matrix-saturate.csv"
	fi
fi

BENCH_PLATFORM="${BENCH_PLATFORM:-ec2}" bash "$ROOT/scripts/bench_write_meta.sh" saturate "$BENCH"

# Tarball for SSM upload (portable: works on macOS + Linux).
TS="$(date -u +%Y%m%dT%H%M%SZ)"
TARBALL="$BENCH/saturate-${TS}.tar.gz"
BUNDLE="$(mktemp -d)"
cp "$REPORT" "$BENCH/matrix.csv" "$BUNDLE/"
[ -f "$HEADLINE_JSON" ] && cp "$HEADLINE_JSON" "$BUNDLE/" || true
[ -f "$BENCH/matrix-saturate.csv" ] && cp "$BENCH/matrix-saturate.csv" "$BUNDLE/" || true
cp "$LOGS"/mpstat_pulsys_* "$BUNDLE/" 2>/dev/null || true
tar -czf "$TARBALL" -C "$BUNDLE" .
rm -rf "$BUNDLE"
chmod 0644 "$TARBALL" 2>/dev/null || true

echo
echo "SATURATE_ARTIFACT=$TARBALL"
echo "SATURATE_REPORT=$REPORT"
