# Dependency review: flags vulnerable or disallowed-license dependencies
# introduced by a pull request before they land on main.
# NOTE: actions are SHA-pinned in the supply-chain hardening pass.

name: dependency-review

on:
  pull_request:

permissions:
  contents: read

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2
        with:
          egress-policy: audit
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4
        with:
          fail-on-severity: high
          comment-summary-in-pr: on-failure
          # Reject copyleft licenses incompatible with Apache-2.0 redistribution.
          deny-licenses: GPL-2.0, GPL-3.0, AGPL-3.0
